/// Disease data constants untuk MVP
/// 3 penyakit: Hawar Daun, Bercak Daun, Busuk Buah

const Map<String, dynamic> leafBlightData = {
  'id': 'leaf_blight_001',
  'slug': 'leaf_blight',
  'name': 'Hawar Daun',
  'english_name': 'Leaf Blight',
  'scientific_names': ['Helminthosporium', 'Alternaria'],
  'description':
      'Hawar daun adalah penyakit yang disebabkan oleh jamur, ditandai dengan munculnya bercak coklat atau hitam pada daun yang dapat menyebar dengan cepat. Penyakit ini dapat menyebabkan kerusakan parah pada tanaman jika tidak ditangani dengan baik.',
  'symptoms': [
    'Bercak coklat atau hitam pada daun',
    'Bercak memiliki lingkaran konsentris (seperti target)',
    'Daun menguning di sekitar bercak',
    'Daun rontok prematur',
    'Penyebaran cepat dalam kondisi lembab',
  ],
  'causes': [
    'Infeksi jamur Helminthosporium atau Alternaria',
    'Kelembaban tinggi (>80%)',
    'Sirkulasi udara buruk',
    'Suhu hangat (20-28°C)',
    'Penyebaran melalui air atau kontak langsung',
  ],
  'treatment': [
    'Pangkas daun yang terinfeksi dan buang jauh dari tanaman',
    'Gunakan fungisida berbahan aktif Mancozeb atau Chlorothalonil',
    'Aplikasi fungisida setiap 7-10 hari',
    'Tingkatkan sirkulasi udara dengan pemangkasan',
    'Hindari menyiram daun, siram di akar saja',
    'Sterilisasi alat pemangkas dengan alkohol',
  ],
  'prevention': [
    'Jaga kelembaban optimal (60-70%)',
    'Siram di pagi hari agar daun cepat kering',
    'Jarak tanam cukup untuk sirkulasi udara',
    'Buang daun yang jatuh',
    'Gunakan benih berkualitas dari sumber terpercaya',
    'Rotasi tanaman setiap musim',
    'Hindari kontak dengan tanaman yang terinfeksi',
  ],
  'severity': 'high',
  'category': 'fungal',
  'affected_plants': ['Tomat', 'Cabai', 'Kentang', 'Bawang', 'Padi'],
  'image_url': 'assets/hawar_daun.jpg',
  'created_at': '2024-12-01T00:00:00Z',
  'updated_at': '2024-12-01T00:00:00Z',
};

const Map<String, dynamic> leafSpotData = {
  'id': 'leaf_spot_001',
  'slug': 'leaf_spot',
  'name': 'Bercak Daun',
  'english_name': 'Leaf Spot',
  'scientific_names': ['Cercospora', 'Septoria', 'Alternaria'],
  'description':
      'Bercak daun adalah penyakit yang ditandai dengan munculnya bercak kecil pada daun dengan berbagai warna (coklat, merah, atau kuning). Penyakit ini berkembang lambat namun dapat mengurangi produktivitas tanaman secara signifikan.',
  'symptoms': [
    'Bercak kecil (2-5mm) pada daun',
    'Bercak berwarna coklat, merah, atau kuning',
    'Halo kuning di sekitar bercak',
    'Bercak dapat bergabung membentuk area besar',
    'Daun menguning dan rontok',
    'Perkembangan lambat dibanding hawar daun',
  ],
  'causes': [
    'Infeksi jamur Cercospora, Septoria, atau Alternaria',
    'Kelembaban tinggi (>70%)',
    'Suhu sedang (15-25°C)',
    'Penyebaran melalui percikan air hujan',
    'Kontak langsung dengan daun yang terinfeksi',
  ],
  'treatment': [
    'Pangkas daun yang terinfeksi parah',
    'Gunakan fungisida berbahan aktif Copper Sulfate atau Mancozeb',
    'Aplikasi fungisida setiap 10-14 hari',
    'Buang sisa tanaman yang terinfeksi',
    'Tingkatkan ventilasi di sekitar tanaman',
    'Hindari menyiram daun',
  ],
  'prevention': [
    'Jaga kelembaban optimal (60-70%)',
    'Siram di pagi hari',
    'Jarak tanam cukup',
    'Buang daun yang jatuh',
    'Gunakan mulsa untuk mengurangi percikan air',
    'Rotasi tanaman',
    'Hindari kontak dengan tanaman terinfeksi',
  ],
  'severity': 'medium',
  'category': 'fungal',
  'affected_plants': ['Tomat', 'Cabai', 'Selada', 'Bawang', 'Stroberi'],
  'image_url': 'assets/bercak_daun.jpg',
  'created_at': '2024-12-01T00:00:00Z',
  'updated_at': '2024-12-01T00:00:00Z',
};

const Map<String, dynamic> fruitRotData = {
  'id': 'fruit_rot_001',
  'slug': 'fruit_rot',
  'name': 'Busuk Buah',
  'english_name': 'Fruit Rot',
  'scientific_names': ['Phytophthora', 'Colletotrichum', 'Fusarium'],
  'description':
      'Busuk buah adalah penyakit yang menyerang buah, menyebabkan pembusukan dan kehilangan hasil panen. Penyakit ini dapat menyebar dengan cepat dan menyebabkan kerugian ekonomi yang besar.',
  'symptoms': [
    'Bercak lembek pada buah',
    'Warna buah berubah menjadi coklat atau hitam',
    'Buah menjadi lembek dan mudah pecah',
    'Mungkin ada pertumbuhan jamur putih atau abu-abu',
    'Bau busuk dari buah yang terinfeksi',
    'Penyebaran cepat ke buah lain yang berdekatan',
  ],
  'causes': [
    'Infeksi jamur Phytophthora, Colletotrichum, atau Fusarium',
    'Kelembaban sangat tinggi (>85%)',
    'Suhu hangat (25-30°C)',
    'Luka pada buah (dari hama atau mekanis)',
    'Penyebaran melalui air atau kontak langsung',
    'Sanitasi buruk',
  ],
  'treatment': [
    'Buang buah yang terinfeksi segera',
    'Gunakan fungisida berbahan aktif Carbendazim atau Propiconazole',
    'Aplikasi fungisida setiap 7-10 hari',
    'Tingkatkan sirkulasi udara',
    'Kurangi penyiraman',
    'Hindari luka pada buah saat panen',
    'Sterilisasi alat panen',
  ],
  'prevention': [
    'Jaga kelembaban optimal (60-70%)',
    'Hindari penyiraman berlebihan',
    'Jarak tanam cukup untuk sirkulasi udara',
    'Buang buah yang jatuh',
    'Panen buah yang matang tepat waktu',
    'Simpan buah di tempat sejuk dan kering',
    'Hindari kontak dengan buah yang terinfeksi',
    'Gunakan mulsa untuk mengurangi percikan air',
  ],
  'severity': 'high',
  'category': 'fungal',
  'affected_plants': ['Tomat', 'Cabai', 'Stroberi', 'Mangga', 'Pisang'],
  'image_url': 'assets/busuk_buah.jpg',
  'created_at': '2024-12-01T00:00:00Z',
  'updated_at': '2024-12-01T00:00:00Z',
};

/// List semua disease data
final List<Map<String, dynamic>> allDiseasesData = [
  leafBlightData,
  leafSpotData,
  fruitRotData,
];
